spring:
  application:
    name: management
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    database: POSTGRESQL
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    baseline-on-migrate: true
    schemas: public
    enabled: true
    validate-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://postgres:5432/skill_craft}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: ${JWT_SECRET}

logging:
  file:
    name: ${LOG_FILE:logs/management.log}
  level:
    root: warn
    org.springframework: warn
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
  pattern:
    console: "%-4r %d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c.%M -> %m%n"
    file: "%-4r %d{yyyy-MM-dd HH:mm:ss} [%t] %-5p %c.%M -> %m%n"

server:
  tomcat:
    max-connections: ${MAX_CONNECTIONS:10}
    accept-count: ${ACCEPT_COUNT:5}
    threads:
      max: ${MAX_THREADS:5}
    keep-alive-timeout: ${KEEP_ALIVE_TIMEOUT:5s}
    connection-timeout: ${CONNECTION_TIMEOUT:5s}
    max-keep-alive-requests: ${MAX_KEEP_ALIVE_REQUESTS:10}
  servlet:
    context-path: "/"
  forward-headers-strategy: FRAMEWORK
  port: ${APP_PORT:8080}
